import frappe
from dhanada.sif.sync.mapper import DataMapper
import json
import os

def check():
    mapper = DataMapper()
    
    dir_path = "/Users/smritisoni/Desktop/AMFI_Fetcher/data/sif/scheme/details/"
    json_files = [f for f in os.listdir(dir_path) if f.endswith(".json")]
    
    raw_schemes = []
    unique_sifs = set()
    
    for fname in json_files:
        with open(os.path.join(dir_path, fname), 'r') as f:
            data = json.load(f)
            raw_schemes.append(data)
            sif = data.get("sif_name")
            if sif:
                sif = str(sif).replace(" SIF", "").strip()
                unique_sifs.add(sif)
                
    print(f"Total JSON files: {len(raw_schemes)}")
    print(f"Unique SIFs found directly from JSON files: {len(unique_sifs)}")
    
    dataset = mapper.map_dataset({"scheme_details": raw_schemes})
    
    print(f"Total AMCs generated by mapper: {len(dataset.amcs)}")
    
    for amc in dataset.amcs[:5]:
        print(f" - AMC Code: {amc.code} | Name: {amc.amc_name} | SIF: {amc.sif_name} | Reg: {amc.registration_number}")

